# Generated by Django 5.2.1 on 2025-06-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop Name')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Owner Name')),
                ('about_shop', models.TextField(blank=True, null=True, verbose_name='About shop')),
                ('shop_contact', models.IntegerField(blank=True, null=True, verbose_name='Shop Number')),
                ('country_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Country Code')),
                ('address', models.TextField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('state', models.CharField(blank=True, max_length=25, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=25, null=True, verbose_name='Country')),
                ('pincode', models.IntegerField(blank=True, null=True, verbose_name='Pincode')),
                ('category', models.CharField(blank=True, max_length=25, null=True, verbose_name='Category')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
