# Generated by Django 5.2.1 on 2025-05-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=15, null=True),
        ),
    ]
