# Generated by Django 5.2.1 on 2025-06-02 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Pincode')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
        ),
    ]
